---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/bbr-pipeline
    tag: final

inputs:
  - name: pcf-pipelines
  - name: binary
  - name: archive

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: pcf-pipelines/tasks/bbr-restore-director/task.sh
